# Generated by Django 5.0.4 on 2024-05-21 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerid', models.CharField(db_column='customerID', max_length=7, primary_key=True, serialize=False)),
                ('latitude', models.CharField(blank=True, max_length=18, null=True)),
                ('longitude', models.CharField(blank=True, max_length=19, null=True)),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sku', models.CharField(db_column='SKU', max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=21, null=True)),
                ('price', models.DecimalField(blank=True, db_column='Price', decimal_places=2, max_digits=4, null=True)),
                ('category', models.CharField(blank=True, db_column='Category', max_length=10, null=True)),
                ('size', models.CharField(blank=True, db_column='Size', max_length=11, null=True)),
                ('ingredients', models.CharField(blank=True, db_column='Ingredients', max_length=65, null=True)),
                ('launch', models.CharField(blank=True, db_column='Launch', max_length=11, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('storeid', models.CharField(db_column='storeID', max_length=7, primary_key=True, serialize=False)),
                ('zipcode', models.IntegerField(blank=True, db_column='zipcode', null=True)),
                ('state_abbr', models.CharField(blank=True, db_column='state_abbr', max_length=2, null=True)),
                ('latitude', models.DecimalField(blank=True, db_column='latitude', decimal_places=6, max_digits=8, null=True)),
                ('longitude', models.DecimalField(blank=True, db_column='longtitude', decimal_places=5, max_digits=9, null=True)),
                ('city', models.CharField(blank=True, db_column='city', max_length=15, null=True)),
                ('state', models.CharField(blank=True, db_column='state', max_length=10, null=True)),
                ('distance', models.CharField(blank=True, db_column='distance', max_length=18, null=True)),
            ],
            options={
                'db_table': 'stores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.IntegerField(db_column='orderID', primary_key=True, serialize=False)),
                ('orderdate', models.CharField(blank=True, db_column='orderDate', max_length=20, null=True)),
                ('nitems', models.IntegerField(blank=True, db_column='nItems', null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('customerid', models.ForeignKey(blank=True, db_column='customerID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_analysis.customer')),
                ('storeid', models.ForeignKey(blank=True, db_column='storeID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_analysis.store')),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.ForeignKey(blank=True, db_column='orderID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_analysis.order')),
                ('sku', models.ForeignKey(blank=True, db_column='SKU', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_analysis.product')),
            ],
            options={
                'db_table': 'orderItems',
                'managed': False,
            },
        ),
    ]
