# Generated by Django 5.0.6 on 2024-06-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0002_alter_piedata_id_alter_totalsalesbymonthbar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalsalesbymonthbar',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
