# Generated by Django 5.0.6 on 2024-06-18 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0003_alter_totalsalesbymonthbar_id'),
    ]

    operations = [
    ]
