# Generated by Django 5.0.6 on 2024-06-21 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0004_auto_20240618_2123'),
    ]

    operations = [
    ]
