# Generated by Django 5.0.6 on 2024-06-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0005_auto_20240622_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyRPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_customers', models.IntegerField()),
                ('repeat_customers', models.IntegerField()),
                ('repeat_purchase_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Monthly RPR',
                'verbose_name_plural': 'Monthly RPRs',
                'db_table': 'monthly_rpr',
            },
        ),
        migrations.CreateModel(
            name='RevenueSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('segment', models.CharField(max_length=10)),
                ('segment_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Revenue Segment',
                'verbose_name_plural': 'Revenue Segments',
                'db_table': 'revenue_segments',
            },
        ),
        migrations.CreateModel(
            name='YearTcRcRpr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('total_customers', models.IntegerField()),
                ('repeat_customers', models.IntegerField()),
                ('repeat_purchase_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'yearTcRcRpr',
            },
        ),
        migrations.AlterField(
            model_name='store',
            name='longitude',
            field=models.DecimalField(blank=True, db_column='longitude', decimal_places=5, max_digits=9, null=True),
        ),
    ]
