# Generated by Django 5.0.6 on 2024-06-23 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0006_monthlyrpr_revenuesegment_yeartcrcrpr_and_more'),
    ]

    operations = [
    ]
