# Generated by Django 5.0.6 on 2024-06-23 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0007_auto_20240623_1338'),
    ]

    operations = [
    ]
