# Generated by Django 5.0.6 on 2024-06-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0009_alter_yeartcrcrpr_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=255)),
                ('usage_count', models.IntegerField()),
                ('usage_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Ingredient Usage',
                'verbose_name_plural': 'Ingredient Usages',
                'db_table': 'ingredient_usage',
            },
        ),
    ]
