# Generated by Django 5.0.6 on 2024-06-30 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0011_storecategoryrevenue'),
    ]

    operations = [
    ]
