# Generated by Django 5.0.6 on 2024-07-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0013_auto_20240630_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderID', models.CharField(max_length=50)),
                ('customerID', models.CharField(max_length=50)),
                ('storeID', models.CharField(max_length=50)),
                ('orderDate', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('customer_lon', models.DecimalField(decimal_places=7, max_digits=10)),
                ('store_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('store_lon', models.DecimalField(decimal_places=7, max_digits=10)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Order Distance',
                'verbose_name_plural': 'Order Distances',
                'db_table': 'order_distances',
                'ordering': ['orderID'],
                'managed': False,  # Hinzugefügt
            },
        ),
        migrations.CreateModel(
            name='OrderDistanceAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_rounded', models.IntegerField()),
                ('order_count', models.IntegerField()),
                ('avg_order_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Order Distance Aggregate',
                'verbose_name_plural': 'Order Distance Aggregates',
                'db_table': 'order_distance_aggregates',
                'ordering': ['distance_rounded'],
                'managed': False,  # Hinzugefügt
            },
        ),
        migrations.CreateModel(
            name='ProductSizePopularity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_size', models.CharField(max_length=50)),
                ('total_sales', models.IntegerField()),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Product Size Popularity',
                'verbose_name_plural': 'Product Size Popularities',
                'db_table': 'product_size_popularity',
                'ordering': ['product_size'],
                'managed': False,  # Hinzugefügt
            },
        ),
        migrations.CreateModel(
            name='StoreRevenueItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('storeID', models.CharField(max_length=50)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_items', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Store Revenue Item',
                'verbose_name_plural': 'Store Revenue Items',
                'db_table': 'store_revenue_items',
                'ordering': ['storeID'],
                'managed': False,  # Hinzugefügt
            },
        ),
    ]
