# Generated by Django 5.0.6 on 2024-07-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0013_auto_20240630_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreRevenueItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('storeID', models.CharField(max_length=50)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_items', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Store Revenue Item',
                'verbose_name_plural': 'Store Revenue Items',
                'db_table': 'store_revenue_items',
                'ordering': ['storeID'],
            },
        ),
    ]
