# Generated by Django 5.0.6 on 2024-07-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0014_orderdistance_orderdistanceaggregate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClvVsOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.CharField(max_length=50)),
                ('total_orders', models.IntegerField()),
                ('clv', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'clv_vs_orders',
            },
        ),
        migrations.CreateModel(
            name='PriceSensitivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'price_sensitivity',
            },
        ),
    ]
