# Generated by Django 5.0.6 on 2024-07-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0014_storerevenueitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderID', models.CharField(max_length=50)),
                ('customerID', models.CharField(max_length=50)),
                ('storeID', models.CharField(max_length=50)),
                ('orderDate', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('customer_lon', models.DecimalField(decimal_places=7, max_digits=10)),
                ('store_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('store_lon', models.DecimalField(decimal_places=7, max_digits=10)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Order Distance',
                'verbose_name_plural': 'Order Distances',
                'db_table': 'order_distances',
                'ordering': ['orderID'],
            },
        ),
        migrations.CreateModel(
            name='OrderDistanceAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_rounded', models.IntegerField()),
                ('order_count', models.IntegerField()),
                ('avg_order_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Order Distance Aggregate',
                'verbose_name_plural': 'Order Distance Aggregates',
                'db_table': 'order_distance_aggregates',
                'ordering': ['distance_rounded'],
            },
        ),
    ]
