# Generated by Django 5.0.6 on 2024-07-05 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0015_clvvsorders_pricesensitivity'),
    ]

    operations = [
    ]
