# Generated by Django 5.0.6 on 2024-07-05 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0016_auto_20240705_1622'),
    ]

    operations = [
    ]
